server:
  port: 8765
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: yewa
    password: 251212
  application:
    name: eurekaclient
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
student: 
  name: 张飞
  age: 28
